### ISSUE TITLE
Does wgpu::Device need to be borrowed mutably ?

### ISSUE THREAD

**Issue by carado** [hecrj/wgpu_glyph#12]
From my own attempts at working with wgpu, it seems like the wgpu::Device only needs to get mutably borrowed for submitting CommandBuffers into the queue.

Indeed, I can run the following line in wgpu_glyph:
```bash
sed -i 's/&mut wgpu::Device/\&wgpu::Device/g' $(find src -iname '*.rs')
```
and the whole crate can still be built without any issue, and its example binary still runs perfectly fine.

**Comment by hecrj** [comment]
You are right, we do not need it.

However, given that `wgpu` is still shaping up, asking for a mutable reference is a safe default. If we end up not needing it once the API stabilizes, then we will be able to drop it without affecting our users much.

**Comment by carado** [comment]
That's fair, thanks for your response.
