### ISSUE TITLE
Update to glyph_brush 0.6

### ISSUE THREAD

**Issue by dhardy** [hecrj/wgpu_glyph#22]
This has a new release out, itself depending on a new rusttype version. It would be nice to have a new release for this.

BTW you can also correct the doc here: https://github.com/hecrj/wgpu_glyph/blob/master/src/lib.rs#L36

**Comment by hecrj** [comment]
`glyph-brush` has already been updated in `master`.

We are currently waiting for a new `wgpu` release.

> BTW you can also correct the doc here: https://github.com/hecrj/wgpu_glyph/blob/master/src/lib.rs#L36

Thanks for the catch! It should be fixed now :)
