### ISSUE TITLE
&mut wgpu::Device does not have to be mutable

### ISSUE THREAD

**Issue by Technici4n** [hecrj/wgpu_glyph#26]
I think that all mutable references to wgpu::Device can be replaced by immutable references, considering that [wgpu::Device has no `&mut self` function](https://docs.rs/wgpu/0.4.0/wgpu/struct.Device.html). Do you think this could be changed?
I can submit a PR myself if you want me to.

Thanks

**Comment by hecrj** [comment]
Yes, that is true. #12 was a similar issue.

Is the mutability requirement an issue for your use case?

**Comment by Technici4n** [comment]
Ah yes it makes sense. No, it's not an issue, it was just a bit... surprising!
