### ISSUE TITLE
Typo in docs

### ISSUE THREAD

**Issue by kanjiwar** [hecrj/wgpu_glyph#45]
https://docs.rs/wgpu_glyph/0.9.0/wgpu_glyph/struct.Text.html

```
scale: PxScale
Position on screen to render text, in pixels from top-left. Defaults to (0, 0).
```

**Comment by hecrj** [comment]
Fixed in `glyph-brush 0.7.1`. Related commit: https://github.com/alexheretic/glyph-brush/commit/e695543fe93d2ca7385f5ef7653a9cc8d9cd0258
