### ISSUE TITLE
Get bounding box of drawn text

### ISSUE THREAD

**Issue by leontepe** [hecrj/wgpu_glyph#86]
I need to know the dimensions of the rendered text after it is drawn or calculate if beforehand. Is there a suitable method for that in this library?

**Comment by hecrj** [comment]
You can use [the `GlyphCruncher` trait](https://docs.rs/wgpu_glyph/latest/wgpu_glyph/trait.GlyphCruncher.html).

**Comment by leontepe** [comment]
Seems like it should do the trick. Thanks.
