### ISSUE TITLE
Font weight problem

### ISSUE THREAD

**Issue by leontepe** [hecrj/wgpu_glyph#87]
The font weight of text rendered with this library seems to be off in comparison to the font rendering used in browsers.

Safari:
<img width="567" alt="Screenshot 2022-01-20 at 10 32 12" src="https://user-images.githubusercontent.com/27787342/150320170-a91444b9-98b2-4530-8340-9f6676c51f0f.png">

wgpu_glyph:
<img width="570" alt="Screenshot 2022-01-20 at 10 33 48" src="https://user-images.githubusercontent.com/27787342/150320738-9090294e-0481-4d7f-bec4-6770e3479f8f.png">

If you look closely, there's a pixel difference between these two—easy to spot at the plus or equals sign. They both don't have any font weight modifications; it's the default font weight.

The same holds true for Firefox and Chrome.

I'm not a font expert, so I have no idea what method would need to be implemented, which one is used in browsers to achieve this, or whether browsers diverge from default OS font rendering in this case.

Nevertheless, the text seems to be just a little bit too thin in comparison. Help would be much appreciated here :-)

Edit: using macOS.

**Comment by hecrj** [comment]
This is probably the result of stem darkening, which `glyph_brush` does not support.

**Comment by leontepe** [comment]
Opened [an issue](https://github.com/alexheretic/glyph-brush/issues/147) for glyph-brush instead then. Thanks.
